# NixOS Snapper configuration

{ config, ... }:

{
	services.snapper.snapshotInterval = "hourly";
	services.snapper.cleanupInterval = "1d";
	services.snapper.configs = {
		root = {
			subvolume = "/";
			extraConfig = ''
				ALLOW_GROUPS=""
				ALLOW_USERS=""
				BACKGROUND_COMPARISON=yes
				EMPTY_PRE_POST_CLEANUP=yes
				EMPTY_PRE_POST_MIN_AGE=1800
				FREE_LIMIT=0.2
				NUMBER_CLEANUP=yes
				NUMBER_LIMIT=50
				NUMBER_LIMIT_IMPORTANT=10
				NUMBER_MIN_AGE=1800
				QGROUP=""
				SPACE_LIMIT=0.5
				SYNC_ACL=no
				TIMELINE_CLEANUP=yes
				TIMELINE_CREATE=yes
				TIMELINE_LIMIT_DAILY=7
				TIMELINE_LIMIT_HOURLY=12
				TIMELINE_LIMIT_MONTHLY=6
				TIMELINE_LIMIT_WEEKLY=4
				TIMELINE_LIMIT_YEARLY=2
				TIMELINE_MIN_AGE=1800
			'';
		};
		home = {
			subvolume = "/home";
			extraConfig = ''
				ALLOW_GROUPS=""
				ALLOW_USERS=""
				BACKGROUND_COMPARISON=yes
				EMPTY_PRE_POST_CLEANUP=yes
				EMPTY_PRE_POST_MIN_AGE=1800
				FREE_LIMIT=0.2
				NUMBER_CLEANUP=yes
				NUMBER_LIMIT=50
				NUMBER_LIMIT_IMPORTANT=10
				NUMBER_MIN_AGE=1800
				QGROUP=""
				SPACE_LIMIT=0.5
				SYNC_ACL=no
				TIMELINE_CLEANUP=yes
				TIMELINE_CREATE=yes
				TIMELINE_LIMIT_DAILY=7
				TIMELINE_LIMIT_HOURLY=24
				TIMELINE_LIMIT_MONTHLY=6
				TIMELINE_LIMIT_WEEKLY=4
				TIMELINE_LIMIT_YEARLY=2
				TIMELINE_MIN_AGE=1800
			'';
		};
		docker = {
			subvolume = "/var/lib/docker";
			extraConfig = ''
				ALLOW_GROUPS=""
				ALLOW_USERS=""
				BACKGROUND_COMPARISON=yes
				EMPTY_PRE_POST_CLEANUP=yes
				EMPTY_PRE_POST_MIN_AGE=1800
				FREE_LIMIT=0.2
				NUMBER_CLEANUP=yes
				NUMBER_LIMIT=50
				NUMBER_LIMIT_IMPORTANT=10
				NUMBER_MIN_AGE=1800
				QGROUP=""
				SPACE_LIMIT=0.5
				SYNC_ACL=no
				TIMELINE_CLEANUP=yes
				TIMELINE_CREATE=yes
				TIMELINE_LIMIT_DAILY=7
				TIMELINE_LIMIT_HOURLY=24
				TIMELINE_LIMIT_MONTHLY=6
				TIMELINE_LIMIT_WEEKLY=4
				TIMELINE_LIMIT_YEARLY=2
				TIMELINE_MIN_AGE=1800
			'';
		};
	};
}
